FROM python:3.13

RUN apt-get update && apt-get install -y git cloc 
WORKDIR /app

COPY . /app

ENV PYTHONPATH="${PYTHONPATH}:/app/src"

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "app.py"]