FROM python:3.13

RUN apt-get update && apt-get install -y git cloc 

ENV PYTHONPATH="/app"
WORKDIR /app

RUN mkdir -p /app/modules
RUN mkdir -p /app/modules/LOC_api

COPY modules/LOC_api/requirements.txt /app/modules/LOC_api/requirements.txt

RUN pip install --no-cache-dir -r /app/modules/LOC_api/requirements.txt

COPY ../../modules/utilities/ /app/modules/utilities/
COPY ../../modules/__init__.py /app/modules/__init__.py

COPY modules/LOC_api/. /app/modules/LOC_api/

EXPOSE 5002

CMD ["python", "/app/modules/LOC_api/app.py"]