services:
  loc:
    build:
      context: .
      dockerfile: DockerfileServices
      args:
        SERVICE_NAME: loc
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network

  mttr:
    build:
      context: .
      dockerfile: DockerfileServices
      args:
        SERVICE_NAME: mttr
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network

  cc:
    build:
      context: .
      dockerfile: DockerfileServices
      args:
        SERVICE_NAME: cc
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network

  defects-over-time:
    build:
      context: .
      dockerfile: DockerfileServices
      args:
        SERVICE_NAME: defects-over-time
    networks:
      - analysis-network

  cyclo:
    build:
      context: .
      dockerfile: DockerfileServices
      args:
        SERVICE_NAME: cyclo
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos

  hal: 
    build: 
      context: .
      dockerfile: DockerfileServices
      args:
        SERVICE_NAME: hal
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
  
  ici: 
    build: 
      context: .
      dockerfile: DockerfileServices
      args:
        SERVICE_NAME: ici
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos

  middleware:
    build:
      context: .
      dockerfile: DockerfileMiddleware
    ports:
      - "${GATEWAY_PORT}:5000"
    environment:
      - SERVICES=cc,loc,mttr,defects-over-time,cyclo,hal,ici
    depends_on:
      - loc
      - cc
      - cyclo
      - hal
      - ici
      - mttr
      - defects-over-time
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network

networks:
  analysis-network:
    name: analysis-network
    driver: bridge

volumes:
  shared-repos:
