services:
  loc_api:
    build: ./modules/LOC_api
    ports:
      - "${LOC_PORT}:5002"
    networks:
      - analysis-network

  mttr_api:
    build: ./modules/MTTR_api
    ports:
      - "${MTTR_PORT}:5003"
    networks:
      - analysis-network

  cc_api:
    build: ./modules/CC_api
    volumes:
      - ./src:/app/src
    ports:
      - "${CC_PORT}:5001"
    networks:
      - analysis-network

  defects-over-time:
    build: ./modules/defects-over-time
    ports:
      - "${DEFECTS_PORT}:5000"
    networks:
      - analysis-network

  controller:
    build: .
    ports:
      - "${CONTROLLER_PORT}:5000"
    environment:
      - DOCKER_ENV=true
    volumes:
      - ./UI_Dashboard:/app/UI_Dashboard
      - ./src:/app
    depends_on:
      - loc_api
      - mttr_api
      - cc_api
    networks:
      - analysis-network

networks:
  analysis-network:
    name: analysis-network
    driver: bridge
