services:
  loc_api:
    build:
      context: .
      dockerfile: DockerfileServices
      args:
        SERVICE_NAME: loc
    volumes:
      - ./src:/app/src
      - shared-repos:/shared/repos
    ports:
      - "${LOC_PORT}:5002"
    networks:
      - analysis-network

  mttr_api:
    build:
      context: .
      dockerfile: DockerfileServices
      args:
        SERVICE_NAME: mttr
    volumes:
      - ./src:/app/src
      - shared-repos:/shared/repos
    ports:
      - "${MTTR_PORT}:5003"
    networks:
      - analysis-network

  cc_api:
    build:
      context: .
      dockerfile: DockerfileServices
      args:
        SERVICE_NAME: cc
    volumes:
      - ./src:/app/src
      - shared-repos:/shared/repos
    ports:
      - "${CC_PORT}:5001"
    networks:
      - analysis-network

  defects-over-time:
    build:
      context: .
      dockerfile: DockerfileServices
      args:
        SERVICE_NAME: defects-over-time
    ports:
      - "${DEFECTS_PORT}:5004"
    networks:
      - analysis-network

  cyclo_api:
    build:
      context: .
      dockerfile: DockerfileServices
      args:
        SERVICE_NAME: cyclo
    ports:
      - "${CYCLO_PORT}:5005"
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos

  hal_api: 
    build: 
      context: .
      dockerfile: DockerfileServices
      args:
        SERVICE_NAME: hal
    ports:
      - "${HAL_PORT}:5006"
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
  
  ici_api: 
    build: 
      context: .
      dockerfile: DockerfileServices
      args:
        SERVICE_NAME: ici
    ports:
      - "${ICI_PORT}:5009"
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos

  clone_repo:
    build:
      context: .
      dockerfile: DockerfileMiddleware
    ports:
      - "5000:5000"
    volumes:
      - shared-repos:/shared/repos
    networks:
      - analysis-network

networks:
  analysis-network:
    name: analysis-network
    driver: bridge

volumes:
  shared-repos:
