services:
  loc_api:
    build: ./modules/LOC_api
    ports:
      - "${LOC_PORT}:5002"
    networks:
      - analysis-network

  mttr_api:
    build: ./modules/MTTR_api
    ports:
      - "${MTTR_PORT}:5003"
    networks:
      - analysis-network

  cc_api:
    build: ./modules/CC_api
    ports:
      - "${CC_PORT}:5001"
    networks:
      - analysis-network

  cyclo_api:
    build: ./modules/CYCLO_api
    ports: 
      - "${CYCLO_PORT}:5005"
    networks:
      - analysis-network
  
  hal_api: 
    build: ./modules/HAL_api
    ports:
      - "${HAL_PORT}:5006"
    networks:
      - analysis-network

  controller:
    build: .
    ports:
      - "${CONTROLLER_PORT}:5000"
    environment:
      - DOCKER_ENV=true
    volumes:
      - ./UI_Dashboard:/app/UI_Dashboard
      - ./src:/app
    depends_on:
      - loc_api
      - mttr_api
      - cc_api
    networks:
      - analysis-network

networks:
  analysis-network:
    name: analysis-network
    driver: bridge
