services:
  loc_api:
    build:
      context: .
      dockerfile: ./modules/LOC_api/Dockerfile
    volumes:
      - ./src:/app/src
      - shared-repos:/shared/repos
    ports:
      - "${LOC_PORT}:5002"
    networks:
      - analysis-network

  mttr_api:
    build:
      context: .
      dockerfile: ./modules/MTTR_api/Dockerfile
    volumes:
      - ./src:/app/src
      - shared-repos:/shared/repos
    ports:
      - "${MTTR_PORT}:5003"
    networks:
      - analysis-network

  cc_api:
    build:
      context: .
      dockerfile: ./modules/CC_api/Dockerfile
    volumes:
      - ./src:/app/src
      - shared-repos:/shared/repos
    ports:
      - "${CC_PORT}:5001"
    networks:
      - analysis-network

  defects-over-time:
    build:
      context: .
      dockerfile: modules/defects-over-time/Dockerfile
    ports:
      - "${DEFECTS_PORT}:5004"
    networks:
      - analysis-network

  cyclo_api:
    build:
      context: .
      dockerfile: ./modules/CYCLO_api/Dockerfile
    ports: 
      - "${CYCLO_PORT}:5005"
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos
  
  hal_api: 
    build: 
      context: .
      dockerfile: ./modules/HAL_api/Dockerfile
    ports:
      - "${HAL_PORT}:5006"
    networks:
      - analysis-network
    volumes:
      - shared-repos:/shared/repos

  controller:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${CONTROLLER_PORT}:5000"
    environment:
      - DOCKER_ENV=true
    volumes:
      - ./UI_Dashboard:/app/UI_Dashboard
      - ./src:/app
    depends_on:
      - loc_api
      - mttr_api
      - cc_api
    networks:
      - analysis-network

networks:
  analysis-network:
    name: analysis-network
    driver: bridge

volumes:
  shared-repos:
    