FROM python:3.13

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    cloc \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
COPY . /app

ENV PYTHONPATH="${PYTHONPATH}:/app/src"


RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5003

CMD [ "python", "app.py" ]
