name: Services Build & Test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    paths:
      - "modules/**"

jobs:
  build-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: Install dependencies and run tests
        run: |
          cd modules/defects-over-time
          pip install -r requirements.txt
          pytest
